export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT = "LOGOUT"
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD'
export const CHANGE_IS_LOGIN = "CHANGE_IS_LOGIN"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const CHANGE_NICKNAME = "CHANGE_NICKNAME"
export const CHANGE_BIRTHDAY = "CHANGE_BIRTHDAY"
export const CHANGE_PHONE = "CHANGE_PHONE"

